### ISSUE TITLE
Impacted highway segments

### ISSUE THREAD

**Issue by c4hendrickson** [orcoastalmgmt/tool_sealevelrise_planning#36]
The lines for impacted highway segments, which seems to encompass most roads, are really large when zoomed out. When you zoom in, the lines look fine.
For example: looking at Seaside with the scale bar at 2mi makes it look like a black blob

**Comment by tchaddad** [comment]
Hi Carl,

I've been messing with the cartography since yesterday, so things are not as they should be. I'll try to get it sorted out this morning, and will let you know when it is fixed.

**Comment by tchaddad** [comment]
I think this is now resolved by the scale-dependent rendering we've added, as well as some cartography changes in the line symbols used. Closing for now - you can re-open if there is still an issue (make sure to clear your cache to see the changes in the map).
