### ISSUE TITLE
Terminology - Velocity Zone

### ISSUE THREAD

**Issue by tchaddad** [orcoastalmgmt/tool_sealevelrise_planning#9]
Velocity zone is not a familiar term - "wave action zone" could be better terminology. Add a simple definition of what this means.

Could change the label in the table to "wave action zone (V zone)". The label will be changed in the layer / legend because of the simplification to 3 hazard zones.

**Comment by tchaddad** [comment]
Suggestion: NFIP Velocity Zone

**Comment by tchaddad** [comment]
Suggestion: Zone of Breaking Waves, 

Citation: NFIP Velocity Zones

**Comment by tchaddad** [comment]
This is how FEMA describes these areas:

> "Coastal areas with a 1% or greater chance of flooding and an additional hazard associated with storm waves. These areas have a 26% chance of flooding over the life of a 30‐year mortgage."

https://www.fema.gov/glossary/zone-v

**Comment by tchaddad** [comment]
Asking @mwreed10 if we should swap the term "Storm Waves" into the attributes of the data layer itself (this will only be seen in the web tool by a user who clicks a relevant polygon).

**Comment by mwreed10** [comment]
> Asking @mwreed10 if we should swap the term "Storm Waves" into the attributes of the data layer itself (this will only be seen in the web tool by a user who clicks a relevant polygon).

Yes that sounds good.

**Comment by tchaddad** [comment]
Velocity Zone references were replaced with "Storm waves" so this item is complete.
